---
- hosts: localhost
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      become: true
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: jenkins dependencies
      become: true
      shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
   
    - name: ensure the repository is configured
      become: true
      shell: 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Install OpenJDK Java
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
         - openjdk-8-jdk


    - name: ensure jenkins is installed
      become: true
      apt: name=jenkins update_cache=yes

    - name: ensure jenkins is running
      become: true
      service: name=jenkins state=started


